# Generated by Django 4.2.30 on 2026-06-28 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('display_name', models.CharField(max_length=255, verbose_name='Отображаемое имя (можно переименовывать)')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('size', models.BigIntegerField(verbose_name='Размер (байт)')),
                ('file', models.FileField(upload_to=files.models.user_directory_path, verbose_name='Файл на диске')),
                ('public_hash', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичная ссылка (UUID)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее скачивание')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
