# Generated by Django 4.2.30 on 2026-07-01 00:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mime_type',
            field=models.CharField(blank=True, default='application/octet-stream', max_length=100, verbose_name='MIME-тип'),
        ),
        migrations.AlterField(
            model_name='file',
            name='public_hash',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичная ссылка (UUID)'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['public_hash'], name='files_file_public__c77a86_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner', '-uploaded_at'], name='files_file_owner_i_2202b9_idx'),
        ),
    ]
