# Generated by Django 4.2.30 on 2026-07-09 02:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_mime_type_alter_file_public_hash_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='file',
            name='files_file_public__c77a86_idx',
        ),
        migrations.RemoveIndex(
            model_name='file',
            name='files_file_owner_i_2202b9_idx',
        ),
        migrations.RemoveField(
            model_name='file',
            name='mime_type',
        ),
        migrations.AlterField(
            model_name='file',
            name='public_hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичная ссылка (UUID)'),
        ),
    ]
